version: '2.3'

networks:
  default:
    name: otus-social-network
    ipam:
      driver: default
      config:
        - subnet: 173.37.0.0/16

services:
  otus_db:
    image: postgres:15
    container_name: postgres
    restart: always
    mem_limit: 800M
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5433:5432"
    volumes:
      - ~/volumes/otus-social-network/pg-data:/var/lib/postgresql/data
    command:
      - "docker-entrypoint.sh"
      - "-c"
      - "max-connections=800"
