spring:
  application:
    name: otus-social-network
  pg-properties:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    schema: otus_social
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000
      pool-name: PostgresHikariCP

security:
  jwt:
    secret: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
    access: 1
    refresh: 30
server:
  port: 8080
  servlet:
    context-path: /api